"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY","django-insecure-local-development-key",)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG","true").lower()=="true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",

    "accounts",
    "articles",
    "comments",
    "knowledge",
    "notifications",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "data" / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://localhost:5173",
    ).split(",")
    if origin.strip()
]

CSRF_COOKIE_NAME = "csrftoken"
<<<<<<< HEAD
SCRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
=======
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
>>>>>>> 8de5a87733a78acc0970c3d9fbee2a0b78f40c31

# 防止超大 Markdown 进入渲染器并占用过多内存
CONTENT_MAX_LENGTH = int(
    os.getenv("CONTENT_MAX_LENGTH", "500000")
)

# 去除商检标题标记后，正文至少需要达到的字符数
CONTENT_MIN_LENGTH = int(
    os.getenv("CONTENT_MIN_LENGTH", "10")
)

# 阶段4的文本片段最大字符数
RAG_CHUNK_SIZE = int(os.getenv("RAG_CHUNK_SIZE", "1000"))
# 相邻片段允许重叠的最大字符数
RAG_CHUNK_OVERLAP = int(os.getenv("RAG_CHUNK_OVERLAP", "150"))
# 小片段合并阈值
RAG_MIN_CHUNK_SIZE = int(os.getenv("RAG_MIN_CHUNK_SIZE", "40"))
# 防止异常文档产生无限数量片段
<<<<<<< HEAD
RAG_MAX_CHUNKS = int(os.getenv("RAG_MAX_CHUNKS", "1000"))
=======
RAG_MAX_CHUNKS = int(os.getenv("RAG_MAX_CHUNKS", "1000"))

# 读取 OpenAI-compatible 服务根地址
MODEL_BASE_URL = os.getenv("MODEL_BASE_URL", "")
# 读取服务密钥， 真实值只来自本机环境
MODEL_API_KEY = os.getenv("MODEL_API_KEY", "")
# 读取 LangExtract/chat 使用的模型名称；不要将它用于 Embedding。
MODEL_NAME = os.getenv("MODEL_NAME", "")
# Embedding 模型独立配置，避免聊天模型名称意外发送到 Embedding API。
EMBEDDING_MODEL = os.getenv(
    "EMBEDDING_MODEL",
    "BAAI/bge-small-zh-v1.5",
)
# 默认使用本地 Sentence Transformers；远程模式需显式配置 openai_compatible。
EMBEDDING_PROVIDER = os.getenv("EMBEDDING_PROVIDER", "local")
# Sentence Transformers 使用的设备，例如 cpu、mps 或 cuda。
EMBEDDING_DEVICE = os.getenv("EMBEDDING_DEVICE", "cpu")
# 读取批量大小
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "32"))
# 读取最大重试次数
EMBEDDING_MAX_RETRIES = int(os.getenv("EMBEDDING_MAX_RETRIES", "2"))
# 读取退避时间
EMBEDDING_RETRY_BACKOFF_SECONDS = float(os.getenv("EMBEDDING_RETRY_BACKOFF_SECONDS", "1"))
# 读取模型请求超时配置
LLM_TIMEOUT_SECONDS = int(os.getenv("LLM_TIMEOUT_SECONDS", "30"))
# 让 Embedding 复用项目超时配置
EMBEDDING_TIMEOUT_SECONDS = LLM_TIMEOUT_SECONDS

# 读取 Chroma 本地持久化目录配置
CHROMA_PERSIST_DIRECTORY = os.getenv("CHROMA_PERSIST_DIRECTORY", "./data/chroma")
# 将相对路径统一解析为相对于 backend 目录的绝对路径
CHROMA_PERSIST_DIRECTORY = str((BASE_DIR / CHROMA_PERSIST_DIRECTORY).resolve()) if not os.path.isabs(CHROMA_PERSIST_DIRECTORY) else CHROMA_PERSIST_DIRECTORY
# 读取固定的 Chroma collection 名称
CHROMA_COLLECTION_NAME = os.getenv("CHROMA_COLLECTION_NAME", "ownerblog_articles")
>>>>>>> 8de5a87733a78acc0970c3d9fbee2a0b78f40c31
