# Generated by Django 5.2.17 on 2026-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlechunk",
            name="article_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="articlechunk",
            name="content_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="articlechunk",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="articlechunk",
            name="section",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
