# Generated by Django 5.2.17 on 2026-09-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("pending_review", "待审核"),
                    ("published", "已发布"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
