# Generated by Django 5.2.17 on 2026-09-03 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="chroma_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="article",
            name="embedding_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="index_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="index_status",
            field=models.CharField(
                choices=[
                    ("not_indexed", "未索引"),
                    ("indexing", "索引中"),
                    ("indexed", "已索引"),
                    ("failed", "失败"),
                    ("stale", "过期"),
                ],
                default="not_indexed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="index_step",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="article",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="moderation_reason",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="taken_down_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taken_down_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="token_down_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("pending+review", "待审核"),
                    ("indexing", "索引中"),
                    ("index_failed", "索引失败"),
                    ("published", "已发布"),
                    ("offline", "已下架"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ModerationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_type", models.CharField(max_length=30)),
                ("object_id", models.PositiveBigIntegerField()),
                ("action", models.CharField(max_length=30)),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(blank=True, max_length=30)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
