# Generated by Django 5.2.17 on 2026-09-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_chroma_error_article_content_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="token_down_at",
        ),
        migrations.AddField(
            model_name="article",
            name="taken_down_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("pending_review", "待审核"),
                    ("indexing", "索引中"),
                    ("index_failed", "索引失败"),
                    ("published", "已发布"),
                    ("offline", "已下架"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
