# Generated by Django 5.2.17 on 2026-10-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0005_remove_article_token_down_at_article_taken_down_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="index_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
